In [23]:
%matplotlib inline
import numpy as np
import matplotlib.pyplot as plt

In [25]:
first_matrix = np.arange(3,12)
first_matrix

array([ 3,  4,  5,  6,  7,  8,  9, 10, 11])

In [26]:
first_matrix.reshape(3,3)

array([[ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [27]:
np.min(first_matrix)

3

In [28]:
np.max(first_matrix)

11

In [29]:
np.mean(first_matrix)

7.0

In [30]:
second_matrix = first_matrix ** 2

In [31]:
second_matrix

array([  9,  16,  25,  36,  49,  64,  81, 100, 121])

In [32]:
third_matrix = np.vstack([first_matrix, second_matrix])

In [33]:
third_matrix

array([[  3,   4,   5,   6,   7,   8,   9,  10,  11],
       [  9,  16,  25,  36,  49,  64,  81, 100, 121]])

In [34]:
np.dot(first_matrix, second_matrix)

4347

In [35]:
third_matrix.reshape(3,3,2)

array([[[  3,   4],
        [  5,   6],
        [  7,   8]],

       [[  9,  10],
        [ 11,   9],
        [ 16,  25]],

       [[ 36,  49],
        [ 64,  81],
        [100, 121]]])